export const BACKGROUND_COLOR = "#222034"//"#25252c"
export const TEXT_SECONDARY_COLOR = '#21c6e8'
export const CTA_COLOR = '#07abf3'

export const ADMIN_ADDRESS = 'k:90f45921e0605560ace17ca8fbbe72df95ba7034abeec7a8a7154e9eda7114eb'
export const CONTRACT_NAME = 'wiz-arena'
export const WIZ_BANK = 'wiz-bank'
export const ITEMS_PER_BLOCK = 40


export const DEFAULT_GAS_PRICE = 0.00000001;
export const MAIN_NET_ID = "mainnet01";
export const TEST_NET_ID = "testnet04";

export const LOAD_USER = 'LOAD_USER';
export const CLEAR_USER = 'CLEAR_USER';

export const SET_NETWORK_SETTINGS = 'SET_NETWORK_SETTINGS';
export const SET_NETWORK_URL = 'SET_NETWORK_URL'
export const SET_CONNECT_WALLET = 'SET_CONNECT_WALLET'

export const SET_REVEAL = 'SET_REVEAL'
export const LOAD_ALL_NFTS = 'LOAD_ALL_NFTS'
export const LOAD_ALL_NFTS_IDS = 'LOAD_ALL_NFTS_IDS'
export const LOAD_USER_MINTED_NFTS = 'LOAD_USER_MINTED_NFTS'
export const GET_NFT_MINT_PRICE = 'GET_NFT_MINT_PRICE'

export const UPDATE_TRANSACTION_STATE = 'UPDATE_TRANSACTION_STATE'
export const CLEAR_TRANSACTION_STATE = 'CLEAR_TRANSACTION_STATE'

export const SET_IS_X_WALLET = 'SET_IS_X_WALLET'

export const SET_BLOCK_ID = 'SET_BLOCK_ID'

export const COUNT_MINTED = 'COUNT_MINTED'

export const LOGOUT = 'LOGOUT'

export const LOAD_OFFERS_MADE = 'LOAD_OFFERS_MADE'
export const LOAD_OFFERS_RECEIVED = 'LOAD_OFFERS_RECEIVED'

export const LOAD_BUYIN = 'LOAD_BUYIN'
export const LOAD_FEE_TOURNAMENT = 'LOAD_FEE_TOURNAMENT'
export const LOAD_MONTEPREMI = 'LOAD_MONTEPREMI'
export const LOAD_SUBSCRIBED = 'LOAD_SUBSCRIBED'

export const STORE_FILTERS_STATS = 'STORE_FILTERS_STATS'
