export const BACKGROUND_DAY_COLOR = "white"
export const BACKGROUND_NIGHT_COLOR = "#25252c"////222034
export const TEXT_SECONDARY_COLOR = '#21c6e8' //#840fb2 viola
export const CTA_COLOR = '#07abf3'
export const TEXT_DAY_COLOR = '#1d1d1f'
export const TEXT_NIGHT_COLOR = 'white'

export const MIN_LEVEL = 122
export const MAX_LEVEL = 375

export const REVEAL_CAP = 3084

export const RING_MINT_PRICE = 4.0

export const NODE_URL = 'api.chainweb.com'
//export const NODE_URL = 'chainweb.ecko.finance'
export const ADMIN_ADDRESS = 'k:90f45921e0605560ace17ca8fbbe72df95ba7034abeec7a8a7154e9eda7114eb'
export const CLERIC_MINT_ADDRESS = "k:9ca8b0b628eb386edafcb66cb90cfd79f349433502e1c1dece1fa097f6801250"
export const CONTRACT_NAME = 'wiz-arena'//'wiz-arena-test3'
export const WIZ_BANK = 'wiz-bank'
export const ITEMS_PER_BLOCK = 40

export const CONTRACT_NAME_WIZA = 'wiza'
export const WIZA_TOKEN_BANK = 'wiza-token-bank'

export const CONTRACT_NAME_EQUIPMENT = 'wiz-equipment'

export const DEFAULT_GAS_PRICE = 0.00000001;
export const MAIN_NET_ID = "mainnet01";
export const TEST_NET_ID = "testnet04";

export const LOAD_USER = 'LOAD_USER';
export const CLEAR_USER = 'CLEAR_USER';

export const SET_NETWORK_SETTINGS = 'SET_NETWORK_SETTINGS';
export const SET_NETWORK_URL = 'SET_NETWORK_URL'
export const SET_CONNECT_WALLET = 'SET_CONNECT_WALLET'

export const LOAD_ALL_NFTS = 'LOAD_ALL_NFTS'
export const LOAD_ALL_NFTS_IDS = 'LOAD_ALL_NFTS_IDS'
export const LOAD_USER_MINTED_NFTS = 'LOAD_USER_MINTED_NFTS'
export const GET_NFT_MINT_PRICE = 'GET_NFT_MINT_PRICE'

export const UPDATE_TRANSACTION_STATE = 'UPDATE_TRANSACTION_STATE'
export const CLEAR_TRANSACTION_STATE = 'CLEAR_TRANSACTION_STATE'
export const HIDE_MODAL_TX = 'HIDE_MODAL_TX'

export const SET_IS_X_WALLET = 'SET_IS_X_WALLET'
export const SET_IS_WALLET_CONNECT_QR = 'SET_IS_WALLET_CONNECT_QR'
export const SET_QR_WALLET_CONNECT_CLIENT = 'SET_QR_WALLET_CONNECT_CLIENT'

export const SET_BLOCK_ID = 'SET_BLOCK_ID'

export const COUNT_MINTED = 'COUNT_MINTED'

export const LOGOUT = 'LOGOUT'

export const LOAD_OFFERS_MADE = 'LOAD_OFFERS_MADE'
export const LOAD_OFFERS_RECEIVED = 'LOAD_OFFERS_RECEIVED'

export const LOAD_BUYIN = 'LOAD_BUYIN'
export const LOAD_FEE_TOURNAMENT = 'LOAD_FEE_TOURNAMENT'
export const LOAD_MONTEPREMI = 'LOAD_MONTEPREMI'
export const LOAD_SUBSCRIBED = 'LOAD_SUBSCRIBED'
export const LOAD_SUBSCRIBED_WIZA = 'LOAD_SUBSCRIBED_WIZA'
export const LOAD_SUBSCRIBED_ELITE = 'LOAD_SUBSCRIBED_ELITE'

export const LOAD_BUYIN_WIZA = 'LOAD_BUYIN_WIZA'
export const LOAD_BUYIN_ELITE = 'LOAD_BUYIN_ELITE'
export const LOAD_FEE_TOURNAMENT_WIZA = 'LOAD_FEE_TOURNAMENT_WIZA'

export const STORE_FILTERS_STATS = 'STORE_FILTERS_STATS'
export const STORE_FILTERS_STATS_EQUIP = 'STORE_FILTERS_STATS_EQUIP'

export const LOAD_WIZARDS_STAKED = 'LOAD_WIZARDS_STAKED'
export const SAVE_WIZA_BALANCE = 'SAVE_WIZA_BALANCE'
export const STORE_CIRCULATING_SUPPLY = 'STORE_CIRCULATING_SUPPLY'
export const STORE_TOTAL_MINED = 'STORE_TOTAL_MINED'
export const STORE_WIZA_NOT_CLAIMED = 'STORE_WIZA_NOT_CLAIMED'

export const SET_SFIDA = 'SET_SFIDA'
export const SET_SFIDA_PVE = 'SET_SFIDA_PVE'
export const SET_AVG_LEVEL_PVP = 'SET_AVG_LEVEL_PVP'

export const SAVE_SALES = 'SAVE_SALES'
export const SAVE_SALES_EQUIPMENT = 'SAVE_SALES_EQUIPMENT'

export const SAVE_RANK = 'SAVE_RANK'

export const SET_WIZARD_SELECTED_SHOP = 'SET_WIZARD_SELECTED_SHOP'

export const SET_KADENA_NAME = 'SET_KADENA_NAME'

export const SELECT_WIZARD = 'SELECT_WIZARD'

export const UPDATE_INFO_TRANSACTION_MODAL = 'UPDATE_INFO_TRANSACTION_MODAL'
export const ADD_TX_KEY_TO_INFO = 'ADD_TX_KEY_TO_INFO'
export const REMOVE_INFO_TX = 'REMOVE_INFO_TX'
export const CLEAR_TRANSACTION_STATE_PACT_CODE = 'CLEAR_TRANSACTION_STATE_PACT_CODE'
export const ADD_TX_TO_SUCCEED = 'ADD_TX_TO_SUCCEED'
export const ADD_TX_KEY_TO_LISTEN = 'ADD_TX_KEY_TO_LISTEN'

export const STORE_WALLET_XP = 'STORE_WALLET_XP'

export const HIDE_NAV_BAR = 'HIDE_NAV_BAR'

/// challenges
export const SET_WIZARD_SFIDATO = 'SET_WIZARD_SFIDATO'
export const SET_CHALLENGES_SENT = 'SET_CHALLENGES_SENT'
export const SET_CHALLENGES_RECEIVED = 'SET_CHALLENGES_RECEIVED'
export const SET_CHALLENGE_REPLAY = 'SET_CHALLENGE_REPLAY'
export const SHOW_WINNER_CHALLENGE = 'SHOW_WINNER_CHALLENGE'

/////// equipment
export const LOAD_ALL_ITEMS_IDS = 'LOAD_ALL_ITEMS_IDS'
export const LOAD_ALL_ITEMS = 'LOAD_ALL_ITEMS'
export const SET_BLOCK_ID_ITEM = 'SET_BLOCK_ID_ITEM'

//// AUTO TOURNAMENTS
export const SET_LOADING_PENDING_TOURNAMENTS = 'SET_LOADING_PENDING_TOURNAMENTS'
export const SET_LOADING_COMPLETED_TOURNAMENTS = 'SET_LOADING_COMPLETED_TOURNAMENTS'
export const SET_PENDING_TOURNAMENTS = 'SET_PENDING_TOURNAMENTS'
export const SET_COMPLETED_TOURNAMENTS = 'SET_COMPLETED_TOURNAMENTS'
export const SORT_AUTO_TOURNAMENTS = 'SORT_AUTO_TOURNAMENTS'

export const SET_TIME_TO_HALVENING = 'SET_TIME_TO_HALVENING'

export const SET_VISUAL_COLORS = 'SET_VISUAL_COLORS'

export const SET_SUBSCRIBERS_PVP = 'SET_SUBSCRIBERS_PVP'
