const itemToUrl = {
    'Ring of Accuracy': "https://storage.googleapis.com/wizarena/equipment/ring_accuracy.png",
    'Ring of Destruction': "https://storage.googleapis.com/wizarena/equipment/ring_of_destruction.png",
    'Ring of Force': "https://storage.googleapis.com/wizarena/equipment/ring_force.png",
    'Ring of Last Defense': "https://storage.googleapis.com/wizarena/equipment/ring_of_last_defense.png",
  'Ring of Life': "https://storage.googleapis.com/wizarena/equipment/ring_life.png",
  'Ring of Lightning': "https://storage.googleapis.com/wizarena/equipment/ring_lightning.png",
  'Ring of Magic Shield': "https://storage.googleapis.com/wizarena/equipment/ring_magic_shield.png",
  'Ring of Power': "https://storage.googleapis.com/wizarena/equipment/ring_of_power.png",
  'Ring of Swift Death': "https://storage.googleapis.com/wizarena/equipment/ring_of_swift_death.png",
  'Ring of Attack +1': "https://storage.googleapis.com/wizarena/equipment/ring_atk_5.png",
  'Ring of Attack +2': "https://storage.googleapis.com/wizarena/equipment/ring_atk_4.png",
  'Ring of Attack +3': "https://storage.googleapis.com/wizarena/equipment/ring_atk_3.png",
  'Ring of Attack +4': "https://storage.googleapis.com/wizarena/equipment/ring_atk_2.png",
  'Ring of Attack +5': "https://storage.googleapis.com/wizarena/equipment/ring_atk_1.png",
  'Ring of Damage +2': "https://storage.googleapis.com/wizarena/equipment/ring_dmg_5.png",
  'Ring of Damage +4': "https://storage.googleapis.com/wizarena/equipment/ring_dmg_4.png",
  'Ring of Damage +6': "https://storage.googleapis.com/wizarena/equipment/ring_dmg_3.png",
  'Ring of Damage +8': "https://storage.googleapis.com/wizarena/equipment/ring_dmg_2.png",
  'Ring of Damage +10': "https://storage.googleapis.com/wizarena/equipment/ring_dmg_1.png",
  'Ring of Defense +1': "https://storage.googleapis.com/wizarena/equipment/ring_def_5.png",
  'Ring of Defense +2': "https://storage.googleapis.com/wizarena/equipment/ring_def_4.png",
  'Ring of Defense +3': "https://storage.googleapis.com/wizarena/equipment/ring_def_3.png",
  'Ring of Defense +4': "https://storage.googleapis.com/wizarena/equipment/ring_def_2.png",
  'Ring of Defense +5': "https://storage.googleapis.com/wizarena/equipment/ring_def_1.png",
  'Ring of HP +4': "https://storage.googleapis.com/wizarena/equipment/ring_hp_5.png",
  'Ring of HP +8': "https://storage.googleapis.com/wizarena/equipment/ring_hp_4.png",
  'Ring of HP +12': "https://storage.googleapis.com/wizarena/equipment/ring_hp_3.png",
  'Ring of HP +16': "https://storage.googleapis.com/wizarena/equipment/ring_hp_2.png",
  'Ring of HP +20': "https://storage.googleapis.com/wizarena/equipment/ring_hp_1.png",
  'Ring of Speed +2': "https://storage.googleapis.com/wizarena/equipment/ring_speed_5.png",
  'Ring of Speed +4': "https://storage.googleapis.com/wizarena/equipment/ring_speed_4.png",
  'Ring of Speed +6': "https://storage.googleapis.com/wizarena/equipment/ring_speed_3.png",
  'Ring of Speed +8': "https://storage.googleapis.com/wizarena/equipment/ring_speed_2.png",
  'Ring of Speed +10': "https://storage.googleapis.com/wizarena/equipment/ring_speed_1.png",
}

export default itemToUrl
