const pendantsRarity = {
    'Pendant of Fire Resistance (low)': 20,
    'Pendant of Fire Resistance (medium)': 28,
    'Pendant of Fire Resistance (high)': 18,
    'Pendant of Acid Resistance (low)': 20,
  'Pendant of Acid Resistance (medium)': 28,
  'Pendant of Acid Resistance (high)': 18,
  'Pendant of Dark Resistance (low)': 20,
  'Pendant of Dark Resistance (medium)': 28,
  'Pendant of Dark Resistance (high)': 18,
  'Pendant of Earth Resistance (low)': 20,
  'Pendant of Earth Resistance (medium)': 28,
  'Pendant of Earth Resistance (high)': 18,
  'Pendant of Ice Resistance (low)': 20,
  'Pendant of Ice Resistance (medium)': 28,
  'Pendant of Ice Resistance (high)': 18,
  'Pendant of Psycho Resistance (low)': 20,
  'Pendant of Psycho Resistance (medium)': 28,
  'Pendant of Psycho Resistance (high)': 18,
  'Pendant of Spirit Resistance (low)': 20,
  'Pendant of Spirit Resistance (medium)': 28,
  'Pendant of Spirit Resistance (high)': 18,
  'Pendant of Sun Resistance (low)': 20,
  'Pendant of Sun Resistance (medium)': 28,
  'Pendant of Sun Resistance (high)': 18,
  'Pendant of Thunder Resistance (low)': 20,
  'Pendant of Thunder Resistance (medium)': 28,
  'Pendant of Thunder Resistance (high)': 18,
  'Pendant of Undead Resistance (low)': 20,
  'Pendant of Undead Resistance (medium)': 28,
  'Pendant of Undead Resistance (high)': 18,
  'Pendant of Water Resistance (low)': 20,
  'Pendant of Water Resistance (medium)': 28,
  'Pendant of Water Resistance (high)': 18,
  'Pendant of Wind Resistance (low)': 20,
  'Pendant of Wind Resistance (medium)': 28,
  'Pendant of Wind Resistance (high)': 18,
  'Pendant of Poison 3 Resistance': 66,
  'Pendant of Confuse Resistance': 66,
  'Pendant of Freeze Resistance': 66,
  'Pendant of Shock Resistance': 66,
  'Pendant of Blind Resistance': 66,
  'Pendant of Paralyze 2 Resistance': 66,
  'Pendant of Fear 2 Resistance': 66
}

export default pendantsRarity
